CREATE TABLE Sucursal ( id INT  IDENTITY PRIMARY KEY NOT NULL,  Nombre VARCHAR(100) NOT NULL, Direccion VARCHAR(150), Contacto VARCHAR(100), Latitud VARCHAR(10), Longitud VARCHAR(10) );

CREATE TABLE Proveedor ( id INT IDENTITY PRIMARY KEY NOT NULL, Nombre VARCHAR(120), Contacto VARCHAR(100), Telefono VARCHAR(15), Direccion VARCHAR(120) );

CREATE TABLE CategoriaProducto ( id INT IDENTITY PRIMARY KEY NOT NULL, Nombre VARCHAR(100) NOT NULL, Restricciones VARCHAR(250));

CREATE TABLE Producto (id INT IDENTITY PRIMARY KEY NOT NULL, Nombre VARCHAR(120) NOT NULL, Descripcion VARCHAR(200), Proveedor INT FOREIGN KEY REFERENCES Proveedor(id), CategoriaProducto INT FOREIGN KEY REFERENCES CategoriaProducto(id));

CREATE TABLE Usuario (id INT IDENTITY PRIMARY KEY NOT NULL, Nombre VARCHAR(120) NOT NULL, Correo VARCHAR(100), Telefono VARCHAR(15), NombreUsuario VARCHAR(30) NOT NULL, Password VARCHAR(100) NOT NULL, Sucursal INT FOREIGN KEY REFERENCES Sucursal(id));

CREATE TABLE Lote (id INT IDENTITY PRIMARY KEY NOT NULL, FechaMaxima VARCHAR(100) NOT NULL, FechaCaducidad VARCHAR(100) NOT NULL);

CREATE TABLE Inventario (id INT IDENTITY PRIMARY KEY NOT NULL, Producto INT NOT NULL FOREIGN KEY REFERENCES Producto(id), Sucursal INT NOT NULL FOREIGN KEY REFERENCES Sucursal(id), FechaIngreso VARCHAR(100)  NOT NULL, Cantidad INT NOT NULL, Lote INT NULL FOREIGN KEY REFERENCES Lote(id), Comentarios VARCHAR(250));

CREATE TABLE Pedido (id INT IDENTITY PRIMARY KEY, SucursalDestino INT NOT NULL FOREIGN KEY REFERENCES Sucursal(id),SucursalOrigen INT NOT NULL FOREIGN KEY REFERENCES Sucursal(id), FechaCreacion VARCHAR(100) NOT NULL, FechaEntrega VARCHAR(100), Estado VARCHAR(50) NOT NULL );

CREATE TABLE DetallePedido (id INT IDENTITY PRIMARY KEY, Pedido INT NOT NULL FOREIGN KEY REFERENCES Pedido(id), Producto INT NOT NULL FOREIGN KEY REFERENCES Producto(id), Inventario INT NOT NULL FOREIGN KEY REFERENCES Inventario(id), Cantidad INT NOT NULL );